### ISSUE TITLE
Avoid too many cat <<EOF

### ISSUE THREAD

**Issue by kameshsampath** [redhat-developer-demos/kubernetes-tutorial#10]
Avoid too many cat <<EOF on the tutorial, it will not work for windows user. Better to provide YAML files for the same to be able run via kubectl apply -f 

@sebastienblanc  @lordofthejars

**Comment by burrsutter** [comment]
The cat option is good to show newbies because it often shows up in the main Kubernetes docs.   The other major benefit to the cat option is that it helps the reader understand exactly what they are about to apply to their cluster.  
The current tutorial shows both cat and .yaml files for these reasons.

**Comment by kameshsampath** [comment]
cat does not work on Windows and majority of our students will be a Windower. So adding file option helps.

**Comment by burrsutter** [comment]
At this time, all of our tutorials require Bash and none support Windows.  Windows powershell/cmd.exe will take a LOT of work.

**Comment by lordofthejars** [comment]
Can I close this?

**Comment by burrsutter** [comment]
Closing, we can revisit when we address WSL2 if needed
