### ISSUE TITLE
Copy button adds additional 2 LF before and 1 LF after

### ISSUE THREAD

**Issue by yanaga** [redhat-developer-demos/kubernetes-tutorial#16]
Whenever you hit the copy button in the tutorial you get 2 additional LF copied before the block and 1 additional LF after the block. Any chance we can remove this annoyance?

**Comment by lordofthejars** [comment]
this is some behaviour of the copy to clipboard extension. NowI have
developed a pure JS copy to clipboard logic instead of using the extension.
When the current PR is merged (I'll do it tomorrow morning) then I'll send
another PR that fixes this.

Missatge de Edson Yanaga <notifications@github.com> del dia dg., 3 de maig
2020 a les 22:13:

**Comment by lordofthejars** [comment]
I think this is fixed with the new version.
